services:
  xmcloud-vercel-integration:
      isolation: ${ISOLATION}
      image: xmcloud-vercel-integration:${SITECORE_VERSION}
      build:
        context: .
        dockerfile: ./docker/build/xmcloud-vercel-int/Dockerfile
        args:
          BASE_IMAGE: mcr.microsoft.com/dotnet/sdk:6.0-nanoserver-1809
          NODEJS_VERSION: 14.15.3
      environment:
        GITHUB_CLIENT_ID: ${XMCLOUD_INT_GITHUB_CLIENT_ID}
        GITHUB_CLIENT_SECRET: ${XMCLOUD_INT_GITHUB_CLIENT_SECRET}
        VERCEL_CLIENT_ID: ${XMCLOUD_INT_VERCEL_CLIENT_ID}
        VERCEL_CLIENT_SECRET: ${XMCLOUD_INT_VERCEL_CLIENT_SECRET}
      volumes:
      - .\integration\sitecore-xm-cloud-vercel-integration:C:\app
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xmcloudint-secure.entrypoints=websecure"
      - "traefik.http.routers.xmcloudint-secure.rule=Host(`${XMCloud_VERCEL_INT_HOST}`)"
      - "traefik.http.routers.xmcloudint-secure.tls=true"
      ports:
      - "3001:3000"